### ISSUE TITLE
Guardar los datos en formato CSV

### ISSUE THREAD

**Issue by LaimeJesus** [facttic/apibueno#2]
Guardar los datos extraidos mediante el proceso de ETL(scrapping), en un formato csv para que pueda ser consultado como opción por la api implementada en [coronavirus-tracker-ap](https://github.com/ExpDev07/coronavirus-tracker-api)

**Comment by josx** [comment]
Acá formato de csbs, https://facts.csbs.org/covid-19/covid19_county.csv
