### ISSUE TITLE
Traducción a español

### ISSUE THREAD

**Issue by josx** [facttic/apibueno#36]
Estaria bueno poder traducir:

- API (parametros, propiedades, modelos, comentarios, etc)
- Textos de SwaggerUI y/o redocs

**Comment by josx** [comment]
Acá empece la traducción inicial al español.

https://github.com/facttic/apibueno/tree/traduccion

Me encontre con el problema que para generar la documentación usa mucho código fuente, nombre de archivos, etc. 

- Obviamente los tests no pasan, pero la API funciona correctamente

**Comment by glmaljkovich** [comment]
ya esta hecho
