### ISSUE TITLE
Consume CSV from this repo

### ISSUE THREAD

**Issue by FacundoMainere** [facttic/apibueno#9]
Create a "falopa" CSV for argentina divided by province and consume it from this repository

**Comment by josx** [comment]
Acá formato de csbs https://facts.csbs.org/covid-19/covid19_county.csv

**Comment by josx** [comment]
Perdón por lo anterior, por el código que hizo  @FacundoMainere  el formato es este, y esta en 3 archivos:

- https://github.com/facttic/apibueno/blob/9-consume-local-data/app/data/time_series_confirmed.csv
- https://github.com/facttic/apibueno/blob/9-consume-local-data/app/data/time_series_deaths.csv
- https://github.com/facttic/apibueno/blob/9-consume-local-data/app/data/time_series_recovered.csv
